/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.userdb;


import com.example.jooq.userdb.tables.Users;

import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * userdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<Record> KEY_USERS_UK_USERS_EMAIL = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_uk_users_email"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<Record> KEY_USERS_UK_USERS_UUID = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_uk_users_uuid"), new TableField[] { Users.USERS.UUID }, true);
}
