/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.userdb;


import com.example.jooq.userdb.tables.Users;


/**
 * Convenience access to all tables in userdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>userdb.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
