include:
  - project: "$CI_PROJECT_PATH"
    file: "$CI_PROJECT_FILE"
    ref: "$CI_PROJECT_REF"
  - local: ci/.gitlab-ci-builddev.yaml

stages:
  - prepare
  - security
  - build
  - deploy

variables:
  APP_NAME: "$CI_PROJECT_NAME"
  BUILD_ENV: "false"
  PROJECT: "$CI_PROJECT_ROOT_NAMESPACE"

  AWS_REGION: ap-east-1
  ECR_REGISTRY: 876622472841.dkr.ecr.ap-east-1.amazonaws.com
  IMAGE_NAME: remy/user-service
  GIT_STRATEGY: clone # clone/fetch/none
  GIT_CHECKOUT: "true"


