name: Build & Push AMD64/ARM64 Image to OCIR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_amd64:
    if: true
    environment: dev
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to OCIR
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.OCIR_REGISTRY }}
          username: "${{ vars.OCIR_NAMESPACE }}/${{ secrets.OCIR_USERNAME }}"
          password: ${{ secrets.OCIR_AUTH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.OCIR_REGISTRY }}/${{ vars.OCIR_NAMESPACE }}/${{ vars.OCIR_REPO }}:latest
            ${{ vars.OCIR_REGISTRY }}/${{ vars.OCIR_NAMESPACE }}/${{ vars.OCIR_REPO }}:${{ github.sha }}
          # no platform because of QME trigger
          # cache GHA
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Native
          provenance: false # faster